name: Fetch Postgres Dynamic Secrets
'on': push
jobs:
  fetch_postgres_dynamic_secrets:
    runs-on: self-hosted
    name: Fetch Postgres Dynamic Secrets1
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Fetch dynamic secrets from Akeyless
        id: fetch-dynamic-secrets
        uses: akeyless-community/akeyless-github-action@v1.0.1
        with:
          access-id: '${{ secrets.ACCESS_ID }}'
          dynamic-secrets: |
            - name: "postgres"
              output-name: "postgres_dynamic_secret"
          access-type: jwt
          export-secrets-to-outputs: true
          export-secrets-to-environment: true
          api-url: 'https://csm.thalescryptolabs.com/akeyless-api/v2/'
      - name: Export Secrets to Environment
        run: >
          echo '${{ steps.fetch-dynamic-secrets.outputs.postgres_dynamic_secret}}' | jq -r 'to_entries|map("POSTGRES_\(.key|ascii_upcase)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
      - name: tisk
        run: >
          echo "$GITHUB_ENV"          
      - name: Verify Vars
        run: |
          echo "host: ${{ env.POSTGRES_HOST }}" >> secrets.txt
          echo "username: ${{ env.POSTGRES_USER }}" >> secrets.txt
               

